Question.destroy_all

questions = Question.create([
                              { question_string: "Would you rather work a job where you interact with people all day or work a job where you are at a desk all day?" },
                              { question_string: "What are we really looking for?" },
                              { question_string: "Would you rather risk getting tricked or give our king sized candies all night?" },
                              { question_string: "Do you or do you not like watching horror films, and why? If you like watching, what's your most favorite?" },
                              { question_string: "Would you rather join Metallica or Backstreet Boys?" },
                              { question_string: "What are your favorite TV shows?" },
                              { question_string: "Pause time or rewind time?" },
                              { question_string: "Would you rather live at the North Pole or the South Pole?" },
                              { question_string: "What do you do to beat stress?" },
                              { question_string: "What's the biggest risk you've ever taken?" },
                              { question_string: "If you were an athlete, 'what would you choose as your walkout song?" },
                              { question_string: "What’s your dream vacation?" },
                              { question_string: "Would you rather have a pet sloth or a pet parrot?" },
                              { question_string: "What is the best career advice you've ever received?" },
                              { question_string: "What is the last book you read?" },
                              { question_string: "Favorite Netflix / Prime Video series to binge on during lockdowns?" },
                              { question_string: "Would you rather have candy for dinner or have candy for breakfast?" },
                              { question_string: "What apps do you use most?" },
                              { question_string: "Describe your dream holiday if money was no limit?" },
                              { question_string: "Do you have any Christmas traditions?" },
                              { question_string: "If you could have an unlimited supply of one thing for the rest of your life, what would it be any why?" },
                              { question_string: "On a scale of 1 – 10, how experienced are you with remote work?" },
                              { question_string: "Assuming you had an office with a view, what would you want the view to be of?" },
                              { question_string: "Do you prefer books or films?" },
                              { question_string: "Favorite movies?" },
                              { question_string: "What music do you normally relate to Christmas?" },
                              { question_string: "Would you rather be absolutely terrified of the dark or be afraid of the the thing underneath your bed?" },
                              { question_string: "Arrive early or arrive late?" },
                              { question_string: "What’s the most random thing in your purse/wallet?" },
                              { question_string: "Where do you spend most of your day?" },
                              { question_string: "Where have you traveled?" },
                              { question_string: "Would you rather become CEO for a day or receive a bonus?" },
                              { question_string: "If you could only take three books to a desert island what would they be?" },
                              { question_string: "If you were sent to live on a space station for three months and only allowed to bring three personal items with you, what would they be?" },
                              { question_string: "What’s your personal heaven?" },
                              { question_string: "What are your favorite pizza toppings?" },
                              { question_string: "When’s the last time you went somewhere for the first time?" },
                              { question_string: "If you created your own country, what would it be called?" },
                              { question_string: "What is the best prank you ever pulled on a coworker?" },
                              { question_string: "Do you have a favorite plant?" },
                              { question_string: "What takes a lot of time but is totally worth it?" },
                              { question_string: "What is something you've done that nobody would expect?" },
                              { question_string: "What hobby would you be a lot of fun to get into?" },
                              { question_string: "Which web browser do you use most?" },
                              { question_string: "Talking or listening?" },
                              { question_string: "When you were young, what did you want to be when you grew up?" },
                              { question_string: "Air guitar or air drums?" },
                              { question_string: "Big wedding or small wedding?" },
                              { question_string: "What is the meaning of Christmas to you?" },
                              { question_string: "What do you highly recommend to most people you meet?" },
                              { question_string: "What’s something new you’ve learned about yourself in the last three months?" },
                              { question_string: "Pick something from your pocket/purse and tell us why that thing is inside there" },
                              { question_string: "Road trip or plane trip?" },
                              { question_string: "What’s the best backhanded compliment you’ve heard / can think of on the spot?" },
                              { question_string: "What are some of the dumbest misadventures you’ve been on?" },
                              { question_string: "What, in your opinion, is the most amazing animal?" },
                              { question_string: "If you’re not from this city, why did you end up here?" },
                              { question_string: "What is your #1 recommendation in this city?" },
                              { question_string: "What is the most unique thing you have within reach of your desk?" },
                              { question_string: "What catchy jingle or bit of advertising has stuck with you all these years?" },
                              { question_string: "What's your best sport or fitness activity while in lockdown?" },
                              { question_string: "What would you do with your “15 minutes of fame”?" },
                              { question_string: "Spring, summer, fall, or winter?" },
                              { question_string: "What smell do you hate that doesn’t seem to bother other people?" },
                              { question_string: "If you could have the power of teleportation right now" },
                              { question_string: "Where would you go and why?" },
                              { question_string: "If you could describe your life as a movie, what genre would it be?" },
                              { question_string: "What are you the biggest fan of?" },
                              { question_string: "Would you rather be able to teleport or fly?" },
                              { question_string: "What’s your go-to WFH beverage? Do you prefer coffee? Tea?" },
                              { question_string: "Massive success by accident or modest success on purpose?" },
                              { question_string: "If you were a vegetable ,what vegetable would you be and why?" },
                              { question_string: "If you could have 3 wishes granted, what would they be?" },
                              { question_string: "Would you rather spend time with other people or at home alone?" },
                              { question_string: "Are you a good or a bad witch/magician?" },
                              { question_string: "If you were to teach one subject, what would it be?" },
                              { question_string: "Sun or moon?" },
                              { question_string: "Would you rather go back in time to talk to your younger self, or receive a message from your older self?" },
                              { question_string: "What is your favorite meal to cook and why?" },
                              { question_string: "What is your worst dance move?" },
                              { question_string: "Name a TV show you think is under-rated. Describe it in a sentence." },
                              { question_string: "Football or soccer?" },
                              { question_string: "Mountains or ocean?" },
                              { question_string: "What about becoming an adult caught you completely off guard?" },
                              { question_string: "If you could turn the ocean into a liquid other than water, which one would you pick?" },
                              { question_string: "If you could only take three albums to a desert island what would they be?" },
                              { question_string: "Have you ever left a 1 star review online?" },
                              { question_string: "Tell us the very first thing you usually do on Christmas Day?" },
                              { question_string: "Would you rather spend a month without Instagram or Facebook?" },
                              { question_string: "Puppies or kittens?" },
                              { question_string: "What would your talent be if you were Miss or Mister World?" },
                              { question_string: "Describe the worst movie you’ve ever watched?" },
                              { question_string: "What is your biggest turn off in a partner?" },
                              { question_string: "If you could eat one food for the rest of your life, what would it be?" },
                              { question_string: "Cooking or being cooked for?" },
                              { question_string: "If you could go on a road trip with any person (dead or alive), 'who would you choose and where would you go?" },
                              { question_string: "What does your perfect burger or sandwich have in it?" },
                              { question_string: "What would you do if you were invisible for 24 hours?" },
                              { question_string: "Vacation or staycation?" },
                              { question_string: "Would you rather give up your dreams and live comfortably or struggle penniless until you pass?" },
                              { question_string: "Tell us about your best Christmas activity!" },
                              { question_string: "Would you rather be an olympic gold medalist or an astronaut?" },
                              { question_string: "Batman or Superman?" },
                              { question_string: "Is there a skill you stopped working on that you would like to revisit?" },
                              { question_string: "Pizza or Chinese food?" },
                              { question_string: "Would you rather put an end to war or world hunger?" },
                              { question_string: "If you had to give up one food forever, what would it be?" },
                              { question_string: "What's your earliest childhood memory?" },
                              { question_string: "If you were stranded on an island, what three items would you want to have with you?" },
                              { question_string: "What is your favorite part about working at the company?" },
                              { question_string: "What most surprised you about working in this industry?" },
                              { question_string: "TV or movies?" },
                              { question_string: "Would you rather take your child to work or your pet?" },
                              { question_string: "What is the best food you have ever eaten?" },
                              { question_string: "Who was your favorite pet?" },
                              { question_string: "Describe your dream wedding if money was no object?" },
                              { question_string: "Do you prefer working remotely or working in an office?" },
                              { question_string: "Would you rather walk to work or drive?" },
                              { question_string: "Would you rather be able to speak all human languages or speak to all animals?" },
                              { question_string: "Any brothers, sisters, or cousins? Which one do you have?" },
                              { question_string: "What things bring joy to you in the workplace?" },
                              { question_string: "If you could pick up a new skill in an instant, what would it be?" },
                              { question_string: "What's your life's biggest dream?" },
                              { question_string: "What is a skill that you think everyone should have?" },
                              { question_string: "Have you ever been a member of a sorority or fraternity?" },
                              { question_string: "What is your favorite book genre to read?" },
                              { question_string: "What’s your silliest memory with your best friend?" },
                              { question_string: "What is your go-to excuse for being late to virtual meetings?" },
                              { question_string: "Win the lottery or land your dream job?" },
                              { question_string: "Do you have any Christmas holiday travel plans? Where to?" },
                              { question_string: "Who is the last person you talked to in IRL?" },
                              { question_string: "What’s the most unique shop or restaurant you’ve been in?" },
                              { question_string: "Have you ever been on a college sports team?" },
                              { question_string: "Would you rather eat candy every day for a month or have no candy for a month?" },
                              { question_string: "Skill or popularity?" },
                              { question_string: "If your pets could talk, what would they say about you?" },
                              { question_string: "What TV show are you hooked on or were recently hooked on?" },
                              { question_string: "Would you rather be an Olympic gold medallist or an astronaut?" },
                              { question_string: "What is the most used emoji on your phone right now?" },
                              { question_string: "What’s a problem you have that might be entirely unique to you?" },
                              { question_string: "What's your middle name?" },
                              { question_string: "Do you watch any TV shows that you pretend you don’t watch when people ask?" },
                              { question_string: "What’s the best location to fully enjoy a good cup of coffee?" },
                              { question_string: "Bad breath or body odor?" },
                              { question_string: "What is the most tedious and/or the most exciting sport to watch?" },
                              { question_string: "What breed of dog do you think you would be?" },
                              { question_string: "Time machine or magic wand?" },
                              { question_string: "What is your favorite mythical creature?" },
                              { question_string: "What’s the hardest part about working virtually for you? The easiest?" },
                              { question_string: "What celebrities share your birthday?" },
                              { question_string: "If you could choose any two famous people to have dinner with who would they be?" },
                              { question_string: "What were words you couldn’t pronounce as a child, so you made up your own?" },
                              { question_string: "What do you dream about at night?" },
                              { question_string: "Where do you see yourself going in the company?" },
                              { question_string: "Would you rather pursue your dreams or have a stable,high-earning job?" },
                              { question_string: "Who is your favorite Disney character?" },
                              { question_string: "As a child, did you trick-or-treat during Halloween? Can you remember the costume you went out with?" },
                              { question_string: "Would you rather listen to country or classical music?" },
                              { question_string: "Are you a morning person or a night person?" },
                              { question_string: "What were some of your favorite activities as a kid?" },
                              { question_string: "What was your least favorite childhood chore and why?" },
                              { question_string: "Patterned or plain?" },
                              { question_string: "Would you rather work from the beach or a mountain cabin?" },
                              { question_string: "What is your favorite season?" },
                              { question_string: "If you could be any animal which would you be?" },
                              { question_string: "Talking pets or talking babies?" },
                              { question_string: "After you woke on the beach, water logged and disoriented, what would you do first?" },
                              { question_string: "If you could only have three apps on your phone, which would you choose?" },
                              { question_string: "What is your preferred communication method and style?" },
                              { question_string: "What is the best event you’ve attended?" },
                              { question_string: "Not including deadlines, how do you motivate yourself to get stuff done?" },
                              { question_string: "How good are you at drawing?" },
                              { question_string: "Name a healthy food you enjoy and an unhealthy food that you find hard to resist." },
                              { question_string: "What is your funniest family story?" },
                              { question_string: "If someone offered you a million dollars to give up your smartphone forever, would you do it?" },
                              { question_string: "If a new volcano formed and the government had an online contest to see what it would be named, what name would you submit?" },
                              { question_string: "Is a good deed that goes unappreciated worthless?" },
                              { question_string: "If you weren't doing your current job, what would your dream job be?" },
                              { question_string: "What's one thing you'll never do again?" },
                              { question_string: "What five items would you bring to a desert island? (Assume you have the basics for survival.)" },
                              { question_string: "Visual learner or verbal learner?" },
                              { question_string: "Social media message or text message?" },
                              { question_string: "What coffee do you drink in your morning meeting?" },
                              { question_string: "What’s something that everyone else seems to love—that you don’t understand?" },
                              { question_string: "If you could live anywhere on this planet, where would you choose to live?" },
                              { question_string: "What two words best describe you?" },
                              { question_string: "What fictional family would you want to be a part of?" },
                              { question_string: "Did you brush your teeth today?" },
                              { question_string: "If you had to give a lecture on one thing, what would it be?" },
                              { question_string: "Would you go in the mother-ship with aliens if they landed on Earth tomorrow?" },
                              { question_string: "What’s the greatest challenge you overcame?" },
                              { question_string: "What are you drinking right now? If nothing, what was the last thing you drank?" },
                              { question_string: "Have you ever installed a doughboy pool?" },
                              { question_string: "What topic could you give the longest presentation on right now with no preparation?" },
                              { question_string: "What do you like most about remote work?" },
                              { question_string: "Do you have any short term goals? What are you looking to achieve within the next year?" },
                              { question_string: "1st thing you are excited to do after getting Covid-19 vaccinated?" },
                              { question_string: "Who is your favorite Disney hero or heroine? Would you trade places with them?" },
                              { question_string: "How long would you last in a zombie apocalypse?" },
                              { question_string: "Who is your favorite cartoon character?" },
                              { question_string: "What is your guilty pleasure?" },
                              { question_string: "What are your favorite songs from your teenage years that you still rock out to when nobody else is listening?" },
                              { question_string: "What's the craziest fashion trend you ever rocked?" },
                              { question_string: "What's your silliest memory with your best friend?" },
                              { question_string: "What dance move are you secretly awesome at?" },
                              { question_string: "What commercial jingle gets stuck in your head all the time?" },
                              { question_string: "What's the worst haircut you ever had?" },
                              { question_string: "What's the best prank you've ever played on someone?" },
                              { question_string: "As a child, what did you want to be when you grew up?" },
                              { question_string: "What are you going to do when you retire?" },
                              { question_string: "What's one sentence you'd like to hear from your boss?" },
                              { question_string: "What is the most important personal attribute that you bring to your job?" },
                              { question_string: "What is one important skill that you think everyone should have?" },
                              { question_string: "There are now 25 hours in a day! How do you spend your extra hour?" },
                              { question_string: "What is one of your greatest work-related achievements?" },
                              { question_string: "What activity helps you relieve stress at work?" },
                              { question_string: "What class did you take in school that helps you with your job?" },
                              { question_string: "Professional, casual or sweatpants?, If there were no dress code, how would you dress for work?" },
                              { question_string: "If you could go back in time and make little changes to your childhood, what is one thing you'd learn and master over the years so you'd be an expert at it today?" },
                              { question_string: "If you won a lottery of $1 billion, what would you do with all the money?" },
                              { question_string: "How would you change your life today if the average life expectancy was 400 years?" },
                              { question_string: "What is the most challenging job you can think of?" },
                              { question_string: "A genie grants you three wishes but none of them can directly benefit you. What would those wishes be?" },
                              { question_string: "If you had to change your name, what would your new name be, and why would you choose that name?" },
                              { question_string: "What are the best and worst purchases you've ever made?" },
                              { question_string: "What is your most treasured material possession?" },
                              { question_string: "What do you never leave the house without other than your phone, keys or wallet?" },
                              { question_string: "Who is your hero, and why?" },
                              { question_string: "What is your earliest childhood memory?" },
                              { question_string: "Who was your favorite teacher in school and how did they impact you?" },
                              { question_string: "If you could choose an age to remain forever, which age would you choose?" },
                              { question_string: "What is one important skill every person should have?" },
                              { question_string: "What was the best thing that happened to you this weekend?, This month?, This year?" },
                              { question_string: "What is your favorite holiday?" },
                              { question_string: "Do you set New Years Resolutions?, What was one of yours this year?, Have you kept it?" },
                              { question_string: "Where would you time-travel, if it were possible?" },
                              { question_string: "If you could have a superpower, what would it be and why?" },
                              { question_string: "If you were the captain of a pirate ship, what would be the name of your ship?" },
                              { question_string: "If you could travel to any other planet (real or fictional), where would you go and why?" },
                              { question_string: "What is your favorite movie?" },
                              { question_string: "Who is your favorite actor/actress?" },
                              { question_string: "What is your favorite book?" },
                              { question_string: "What is your favorite tv series?" },
                              { question_string: "What show on Netflix did you binge watch embarrassingly fast?" },
                              { question_string: "If you could be any fictional character, who would you be?" },
                              { question_string: "What type of music do you listen to?" },
                              { question_string: "What movie can you rewatch over and over again?" },
                              { question_string: "If you had to delete all but 3 apps from your smartphone, which ones would you keep?" },
                              { question_string: "When did you get your first cell phone?, What kind was it?" },
                              { question_string: "If you had to choose between only having a cell phone or a car for the rest of your life, which would you choose?" },
                              { question_string: "How many Facebook friends do you have?, How many of them do you actually communicate with?" },
                              { question_string: "What technology innovation made the most impact on your life?" },
                              { question_string: "Desktop, laptop, or tablet?, Which do you prefer to use?" },
                              { question_string: "What is your favorite thing about technology?, Least favorite?" },
                              { question_string: "Have you ever been out of the country?" },
                              { question_string: "Have you ever ridden on a motorcycle?" },
                              { question_string: "Have you ever lived in another state?" },
                              { question_string: "Have you ever met a celebrity?" },
                              { question_string: "Have you ever been to Disney Land or Disney World?" },
                              { question_string: "Have you ever planted a garden?" },
                              { question_string: "Have you ever experienced a natural disaster like a hurricane or tornado?" },
                              { question_string: "Have you ever won a contest?" },
                              { question_string: "Have you ever eaten a whole pizza by yourself?" },
                              { question_string: "Have you ever done any extreme sports like skydiving or bungee jumping?" },
                              { question_string: "What is your favorite hobby?" },
                              { question_string: "What is your favorite sport or physical activity?" },
                              { question_string: "What is your idea of fun?" },
                              { question_string: "What two things do you consider yourself to be very good at?" },
                              { question_string: "What two things do you consider yourself to be very bad at?" },
                              { question_string: "If money and time were no object, what would you be doing right now?" },
                              { question_string: "Do you have any hidden talents?, What can you do?" },
                              { question_string: "Favorite grocery item while shopping locally?" },
                              { question_string: "What is your favorite restaurant?" },
                              { question_string: "If you could only eat one item of food for the rest of your life, what would you eat?" },
                              { question_string: "What is your favorite candy or treat?" },
                              { question_string: "Sweet, salty, or sour?" },
                              { question_string: "What's the weirdest food you've ever eaten?" },
                              { question_string: "What is something you are great at cooking?" },
                              { question_string: "What is your favorite dessert?" },
                              { question_string: "If you could eliminate one food so no one could eat it ever again, what would you destroy?" },
                              { question_string: "What is your favorite breakfast? Lunch? Dinner?" },
                              { question_string: "Do you have any pets?, What are their names?" },
                              { question_string: "Are you a cat person or a dog person?" },
                              { question_string: "What is your spirit animal? (The animal who is most similar to your personality." },
                              { question_string: "What is your favorite animal?" },
                              { question_string: "What famous animal movie character do you like the most?" },
                              { question_string: "Are there any specific animals you are afraid of? Why?" },
                              { question_string: "What is the funniest thing one of your pets have done?" },
                              { question_string: "What is your favorite zoo animal?" },
                              { question_string: "If you were a fish, what type would you be?" },
                              { question_string: "If you had your human body, but the head of an animal, what animal would you pick?" },
                              { question_string: "What's the best trip (traveling wise) you ever had?" },
                              { question_string: "What's your favorite thing about the place where you live?" },
                              { question_string: "If you could live anywhere in the world for a year where would it be?" },
                              { question_string: "Where is your favorite vacation spot?" },
                              { question_string: "What's your favorite seat on an airplane?" },
                              { question_string: "Have you ever been on a cruise? Where did you go?" },
                              { question_string: "Do you enjoy the outdoors? What's your favorite outdoor activity?" },
                              { question_string: "How many countries have you visited outside your own?" },
                              { question_string: "What is your favorite weekend trip?" },
                              { question_string: "Who is your favorite person to travel with?" },
                              { question_string: "What is your favorite theme park?" },
                              { question_string: "In your opinion, what is the most beautiful place on earth?" },
                              { question_string: "Beach, safari, or forest vacation?" }
                            ])

puts "Created #{Question.count} questions"
